### ISSUE TITLE
v1.3.2 To Do

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1862]
# v.1.3.2

- [x] #1381 Add share option for Projects in native apps.
link should be /project/project-name

- [x] Currency localization in Apps #1887 

- [x] #2037 Disable or fix network connection status check & display

- [x] #1365 Update npm dependencies

- [x] #1927 Separate Url for API
- [x] #1678 Fix competition end date

- [x] Assign images in Leaderboard for users without profile pictures @jmiridis @haideralishah 

- [x] Allow to edit and delete all tree registrations @jmiridis  [change mayupdate=true]

- [x] #1959 Label in Leaderboard for Private Users

- [x] Fix issue in Single Contribution (Project is not being loaded correctly) @ankitecd  #1991 

- [x] Improve Headers

- [x] Review functionality missing in the app #1922 

# v1.3.1

- [x] #1831 Merge My Trees to Home and Move Redeem Trees, Dedicate, and Register Trees inside My Trees. @harshvitra 

- [x] Do not load all tree counters of followers, or participants, when loading single treecounter or competition #1631 

- [x] Implement Single Contribution #1859 @ankitecd 

- [x] Rename Competition in bottom menu to Compete
- [x] Get Better icons for Leaderboard

- [x] If a user has dedicated trees, start the donation process with the trees being supported to that individual @mahmed0715 
- [x] Implement profile icons (not image)  instead of tree in Bottom Menu @harshvitra 

- [x] #1792 Implement Clean Headers for all Main pages in the Menu // getting rid of green header

- [x] Add Me to bottom Menu, when logged out.--> redirects to login page. @jmiridis v1.4

- [x] Remove Register trees From Bottom Navigation Menu @harshvitra 

- [x] Fix the issue with `Register Multiple Trees` in Android has same form as Single Trees. @sanjayradadiya 

- [x] Use the progress bar from Projects in Competition preview and single pages as well. @mahmed0715

**Comment by norbertschuler** [comment]
What about versions 1.3.1 and 1.3.2?

**Comment by sanjayradadiya** [comment]
@norbertschuler @sagararyal here is the PR for same form issue
https://github.com/Plant-for-the-Planet-org/treecounter-app/pull/1865

https://www.loom.com/share/b97aaed5c8f242c6a03b0e7d0d89ce12

**Comment by harshvitra** [comment]
Just some sample design for Leaderboard Icons. 

@sagararyal has suggested to make the tone little lighter, so I'll work on that 

![Explore – Leaderboard – 1](https://user-images.githubusercontent.com/25605193/73165930-d4996800-411a-11ea-9362-b94bac244b20.png)

**Comment by mahmed0715** [comment]
@sagararyal please explain a little bit `If a user has dedicated trees, start the donation process with the trees being supported to that individual @mahmed0715`

**Comment by sagararyal** [comment]
@mahmed0715 API  loaduserprofile has

```
  "supportedTreecounter": {
        "id": 112679,
        "displayName": "Jorgo Miridis",
        "avatar": "5c44c070190fd515145730.png",
        "countPlanted": "2.20"
```

In this case, please assign the donation as being supported to this user, as long as the user does not come from Gift, Support Link, or Support button.

**Comment by norbertschuler** [comment]
Accidentally closed this with a merge. 
@sagararyal are these still the open TO-DO‘s for 1.3.2?

**Comment by harshvitra** [comment]
>  Bump the version for redeem trees to fully support New UI
I and Jorgo were discussing this, it would be better to add this in the new backend or it will be double work. 
@sagararyal what would be your call ?
