### ISSUE TITLE
Todo left from Single Contribution Feature

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/treecounter-app#1878]
#1859 

# P3
Comment the buttons and create a New issue for:
- [ ] Give option to download certificate - @sagararyal  what should the certificate contain ? 

- [ ] Give Share function - @sagararyal  what should the share message contain ? 

# P4
- [ ] Add measurement feature (@jmiridis ) need to build a form.

---
# Maps

- [x] The Apple Maps Logo is partially covered (can be a reason for Apple to reject the app!) @haideralishah 
- [x] The Google Logo is partially covered as well on Android devices @haideralishah 

**Update: I think the whole date and number format system currently is broken for the native apps as the retrieval of the locale does not work any more - the formatting in the code is still there, but just does not work any more at all:**
- [x] The date does not get localized e.g. into German date format (display "January" instead of "Januar" - yes, the screenshot below is o.k. as it is made in English) @harshvitra
